source:
  type: mysql
  name: MySQL Source
  hostname: mariadb-main
  port: 3306
  username: root
  password: main_root_password
  tables: my_database.page, my_database.revision, my_database.slots, my_database.content
  server-id: 5401-5404
  scan.startup.mode: earliest-offset

sink:
  type: kafka
  name: Kafka Sink
  properties.bootstrap.servers: PLAINTEXT://broker:29092
  sink.add-tableId-to-header-enabled: true

pipeline:
  name: MediaWiki MariaDB to Kafka Pipeline
  parallelism: 4

# transform:
#   - source-table: my_database.revision
#     projection: \*, FROM_BASE64(rev_timestamp) as rev_timestamp_decoded
#     description: convert timestamps
