# Run download_dependencies.sh before using this Dockerfile.

FROM flink:1.17.0-scala_2.12 AS flink-base
USER flink:flink


# Directory to which download_dependencies.sh pre-downloaded deps.
ARG DEPENDENCY_DIR

# == Add lib, opt and conf to /opt/flink
ADD $DEPENDENCY_DIR/flink /opt/flink

USER root:root
RUN chown -R flink:flink /opt/flink
USER flink:flink

# === Get flink-cdc dist and add lib files to /opt/flink-cdc

# flink-cdc dist allows us to run flink-cdc pipeline launcher script
ADD $DEPENDENCY_DIR/flink-cdc /opt

# paimon action jars (for launching paimon pipelines via CLI)
ADD $DEPENDENCY_DIR/paimon-action /opt/paimon-action

# chmod dirs back to flink so e.g. log/ dirs can be written to
USER root:root
RUN chown -R flink:flink /opt/flink-cdc-*
RUN chown -R flink:flink /opt/paimon-action
USER flink:flink

# hive-metastore-standalone expects hive warehouse at /user/hive/warehouse.
USER root:root
RUN mkdir -p /user/hive/warehouse && chown -R flink:flink /user/hive/warehouse && chmod -R 777 /user/hive/warehouse
USER flink:flink

ENV FLINK_HOME=/opt/flink

